FROM node:20-bullseye as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# Default nginx config is fine for now
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
