services:
  - type: web
    name: codecompiler-cewu
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js

    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHONPATH
        value: /app/user_packages

    aptPackages:
      - openjdk-17-jdk
      - python3
      - python3-pip
      - python3-tk
